name: Rust Lint Test

on:
  pull_request:
    branches: [master]

jobs:
  rust_lint_tests:
    name: Run Clippy & Rustfmt lint tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v1

      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features 

  rust_tests:
    name: Rust tests
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
       
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features